# Generated by Django 3.2.7 on 2025-08-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocStatusFeedback',
            fields=[
                ('doc_job_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('doc_domain_description', models.CharField(max_length=200)),
                ('doc_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KbStatus',
            fields=[
                ('kb_job_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
